name: Deploy test

on:
  push:
    branches:
      - master
      - dev
jobs:
  deploy:
    name: Deploy test222
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello.."
