version: 2
name: 生产环境发布
description: ""
global:
  concurrent: 1
workflow:
  - ref: start
    name: 开始
    task: start
  - ref: nodejs_build_0
    name: nodejs构建
    task: nodejs_build@1.7.0-node18
    input:
      workspace: ((git_clone_0.git_path))
      build_action: '"build"'
      build_args: '""'
      install_args: '""'
      registry_url: '""'
      disturl_url: '""'
      sass_binary_site_url: '""'
      package_management_type: '"yarn"'
      vc_package_dir: '"."'
      cache_path: '"/cache"'
    needs:
      - git_clone_0
  - ref: git_clone_0
    name: git clone
    task: git_clone@1.2.9
    input:
      remote_url: '"https://www.gitlink.org.cn/gitlink/gitlink_help_center.git"'
      ref: '"refs/heads/master"'
      commit_id: '""'
      depth: 1
    needs:
      - start
  - ref: end
    name: 结束
    task: end
    needs:
      - ssh_cmd_0
  - ref: scp_resource_0
    name: scp替换打包文件到服务器
    task: scp_resource@1.4.3
    input:
      ssh_pass: ((help_pro_server.password))
      ssh_ip: '"106.75.45.236"'
      ssh_port: '"22"'
      ssh_user: '"root"'
      remote_file: '"/root/gitlink_help_center/build2"'
      local_file: ((git_clone_0.git_path))+"/build"
      file_content: '""'
    needs:
      - nodejs_build_0
  - ref: ssh_cmd_0
    name: ssh执行命令
    task: ssh_cmd@1.1.1
    input:
      ssh_ip: '""'
      ssh_port: '"22"'
      ssh_user: '"root"'
      ssh_cmd: '""'
    needs:
      - scp_resource_0

